language: ruby

deploy:
  provider: heroku
  api_key:
     secure: "PkcV0vIMXBMIVUyyRC4ELGjj0uQWbTtCWYjO6q3/UQ1W3Q7bOrf3dbvFb5TUO0Ix/VCSY8dsYERmEmn15oGHW6OILFjOaMW2khmJFeA58bckZ1WlxK7ANdBWJqSmXOBZkajpZ6+d2fINs+MaxgrAvJSDdnKHrZQ/yGPqm8tqiyA2w/7FlBLVYuA0fdvSj2s59my459DRGz9hSHJNw3EVd5ZzyEeThKu4+yzWoizNtoG4Uygn8e2CPRS/jDkUHCNcj2fe7CarrlsDxqqV6qz4GC4yIjaUHJFxa/kxVn39ZmbwioLdTEZHPttf087cF3+LptQ81zfsfmECqh6ZLjs9z47ZZ5rD7JjegQ+tvdTVfkH4PMDnfjkga+9MJ6K8GMHYiCaqD/qxm005lQW/Hz/FVffCgN8QxMOuvC+mZOvrMfIkLH627jfcijjydoS7W+F/DkZrNLILJzEcuScjY44XciapvCmoZXGGyateA/EXTL//zwYzUZF6xkAbZv09IIQ8tq/RBUH0N1MH/bL9wtD7pCm3NOwRMd5d5libbn6Ok8zIUMlXZDw0OybjqJwSrCP7FJTmt3d/j0tIJJHvb6GQzWzrI/m2yfpykBpTVwGqpVUkxce36W5I7BL5ekW8JUHBJyWKPpRa9rMnvDsCmhvTOgFJRC2mu6cl8Nf9L6MTcRg="
  app: secret-savannah-44807
  on:
    repo: nax2uk/13581

